name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create bin directory
      run: |
        mkdir -p ${{ runner.workspace }}/bin 

    - name: Get dependencies
      env: 
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: off
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            ${{ runner.workspace }}/bin/dep ensure
        fi

    - name: Build
      env:
        GOPATH: ${{ runner.workspace }}
        GO111MODULE: off
      run: go build -v .
